// Generated by CoffeeScript 1.6.3
(function() {
  var app, express;

  express = require("express");

  app = express();

  app.set('views', "" + __dirname + "/views");

  app.get("/", function(req, res) {
    return res.render("index.html.jade");
  });

  app.get("/download", function(req, res) {
    res.set('Content-type', 'application/chrome-extension');
    res.attachment("" + __dirname + "/oneclick-fontchanger.crx");
    return res.sendFile("" + __dirname + "/oneclick-fontchanger.crx");
  });

  app.listen(4000, function() {
    return console.log("Starting Server on port 4000");
  });

}).call(this);
